### PR TITLE
Added GitHub Action

### PR DESCRIPTION
**Pull request by MarketingPip**
Added a GitHub action for this project. You can find the action here.

[OCR PDF Action: A GitHub action for turning scanned PDF's into searchable documents](https://github.com/MarketingPipeline/OCR-PDF-Action)

:+1:

### CODE REVIEW

**Comment by jbarlow83** [comment]
Is this legitimate use of GitHub Actions?

**Comment by jbarlow83** [comment]
GitHub Actions is intended primarily for CI/CD of software.
https://docs.github.com/en/site-policy/github-terms/github-terms-for-additional-products-and-features#actions

>any activity that places a burden on our servers, where that burden is disproportionate to the benefits provided to users (for example, don't use Actions as a content delivery network or as part of a serverless application, but a low benefit Action could be ok if it’s also low burden); or

I believe using OCRmyPDF as a GitHub Action would be treating the service as a serverless application, and since OCR is CPU intensive, it would not qualify as a low burden.

I am open to discussion - perhaps there's a practical and justifiable use that I'm not seeing. But I'll need to be convinced that this is not violating the Terms of Service.

**Comment by MarketingPip** [comment]
> GitHub Actions is intended primarily for CI/CD of software.
> 
> https://docs.github.com/en/site-policy/github-terms/github-terms-for-additional-products-and-features#actions
> 
> 
> 
> >any activity that places a burden on our servers, where that burden is disproportionate to the benefits provided to users (for example, don't use Actions as a content delivery network or as part of a serverless application, but a low benefit Action could be ok if it’s also low burden); or
> 
> 
> 
> I believe using OCRmyPDF as a GitHub Action would be treating the service as a serverless application, and since OCR is CPU intensive, it would not qualify as a low burden.
> 
> 
> 
> I am open to discussion - perhaps there's a practical and justifiable use that I'm not seeing. But I'll need to be convinced that this is not violating the Terms of Service.

As far as I know, there is NO violation of terms of service. 

Too better understand tho, I'd even be willing to allow yourself etc to message the GitHub team and ask if the action is a violation etc.

As said - as I know there is none, but I don't want to make any false claims.

**Comment by jbarlow83** [comment]
I will leave it to you to contact GitHub and obtain their approval. Please post their response here.

**Comment by MarketingPip** [comment]
@jbarlow83 - will do! I obviously would not want to violate the terms or publish any work that does this. So I will confirm but I am under the assumption until now this is allowed.

**Comment by MarketingPip** [comment]
You can keep this PR open.. 
image

Still in the process of waiting for a reply via GitHub. Tho again - I do NOT believe this violates any TOS...  

If this was the case I would have NOT published it.

**Pull request closed without merging**
